server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    gateway:
        routes:
          - id: user-service
            uri: lb://USER-SERVICE
            predicates:
              - Path=/auth/**
            filters:
              - name: AuthenticationFilter
          - id: food-service
            uri: lb://FOOD-SERVICE
            predicates:
              - Path=/food/**
            filters:
              - name: AuthenticationFilter
          - id: cart-service
            uri: lb://CART-SERVICE
            predicates:
              - Path=/cart/**
            filters:
              - name: AuthenticationFilter
          - id: order-service
            uri: lb://ORDER-SERVICE
            predicates:
              - Path=/orders/**
            filters:
              - name: AuthenticationFilter
          - id: image-service
            uri: lb://IMAGE-SERVICE
            predicates:
              - Path=/images/**
            filters:
              - name: AuthenticationFilter
          - id: payment-service
            uri: lb://PAYMENT-SERVICE
            predicates:
              - Path=/payments/**
            filters:
              - name: AuthenticationFilter
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/