server:
  port: 8086
spring:
  application:
    name: payment-service
  datasource:
    url: jdbc:postgresql://localhost:5432/slicemate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    listener:
      simple:
        retry:
          enabled: true
          initial-interval: 1000
          max-attempts: 3
          multiplier: 2.0
          stateless: true
        acknowledge-mode: auto
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/