server:
  port: 8081
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:postgresql://localhost:5432/slicemate
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 814338473524-8omor683i5is57btgii69aief4of30c5.apps.googleusercontent.com
            client-secret: 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
            scope: openid, profile, email
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: sliceMate-secret-key
  expiration: 3600000
