server:
  port: 8083
spring:
  application:
    name: image-service
  servlet:
    multipart:
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
resilience4j:
  circuitbreaker:
    instances:
      authService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
      foodService:
        failureRateThreshold: 60
        waitDurationInOpenState: 7000ms
        permittedNumberOfCallsInHalfOpenState: 3
        slidingWindowSize: 15
      paymentService:
        failureRateThreshold: 50
        waitDurationInOpenState: 5000ms
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10
      userService:
        failureRateThreshold: 50
        waitDurationInOpenState: 6000ms
        permittedNumberOfCallsInHalfOpenState: 2
        slidingWindowSize: 10

  retry:
    instances:
      paymentService:
        maxAttempts: 3
        waitDuration: 2000ms
      foodService:
        maxAttempts: 2
        waitDuration: 3000ms
      userService:
        maxAttempts: 3
        waitDuration: 2000ms

